language: php

dist: trusty

# Wait until travis bug fixes
sudo: require

branches:
  only:
    - master
    - /^(?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+)$/

services:
  - mysql

cache:
  apt: true
  yarn: true
  directories:
    - $HOME/.composer/cache/files

addons:
  apt:
    packages:
      - nginx

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 7.0
  - 7.1

env:
  global:
    - COMPOSER_NO_INTERACTION=1
  matrix:
    - WP_VERSION=nightly
    - WP_VERSION=latest WITH_COVERAGE=true

before_install:
  # Set environment variables
  - if [[ $(phpenv version-name) == "nightly" ]]; then export WITH_COVERAGE=false; fi

  # Disable xDebug to speed up the build unless test coverage is needed
  - if [[ "$WITH_COVERAGE" != "true" && $(phpenv version-name) != "nightly" ]]; then phpenv config-rm xdebug.ini; fi

  # Install helper scripts
  - travis_retry composer global require --prefer-dist --no-suggest typisttech/travis-nginx-wordpress
  - export PATH=$HOME/.composer/vendor/bin:$PATH
  - tnw-install-nginx
  - tnw-install-wordpress
  - tnw-prepare-codeception

  # Enable WP_DEBUG
  - wp core config --dbname=wordpress --dbuser=root --dbhost=localhost --locale=$en_US --force --path=/tmp/wordpress/ --extra-php="define( 'AUTOMATIC_UPDATER_DISABLED', true ); define( 'WP_DEBUG', true );"

  # Build the production plugin
  - travis_retry composer build
  # Activate the plugin
  - wp plugin install ./release/sunny.zip --force --activate --path=/tmp/wordpress
  # Export a dump of plugin-activated database to the _data folder
  - wp db export $TRAVIS_BUILD_DIR/tests/_data/dump.sql --path=/tmp/wordpress

install:
  - travis_retry composer install --prefer-dist --no-suggest

script:
  - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/codecept run integration,unit --coverage --coverage-xml; fi
  - if [[ "$WITH_COVERAGE" != "true" ]]; then vendor/bin/codecept run integration,unit; fi

  - vendor/bin/codecept run functional
  - vendor/bin/codecept run acceptance

  # WP REST API testing
  - rm -dfr /tmp/wordpress/wp-content/plugins/sunny
  - cp -R $TRAVIS_BUILD_DIR /tmp/wordpress/wp-content/plugins/sunny
  - cd /tmp/wordpress/wp-content/plugins/sunny
  - vendor/bin/codecept run restapi

  # Go back to build directory
  - cd $TRAVIS_BUILD_DIR

after_script:
  - if [[ "$WITH_COVERAGE" == "true" ]]; then travis_retry tnw-upload-coverage-to-scrutinizer; fi
  - if [[ "$WITH_COVERAGE" == "true" ]]; then travis_retry tnw-upload-coverage-to-codecov; fi

before_deploy:
  # Install
  - travis_retry composer install --prefer-dist --no-suggest
  # Build the production plugin
  - travis_retry composer build
  - unzip -qo release/sunny.zip -d build

deploy_default: &deploy_default
  stage: deploy
  php: 7.0
  addons: []
  services: []
  before_install: skip
  # Wait for DPL supports Ruby 2.3.x
  install: rvm install 2.2.7
  script: skip
  after_script: skip
  deploy:
  on:
    repo: TypistTech/sunny

jobs:
  include:
    - <<: *deploy_default
      env: DEPLOY=GITHUB_RELEASE_ARTIFACTS
      deploy:
        provider: releases
        api_key: $GITHUB_ACCESS_TOKEN
        file: release/sunny.zip
        on:
          tags: true
    - <<: *deploy_default
      env: DEPLOY=WORDPRESS_PLUGIN
      deploy:
        provider: wordpress-plugin
        edge:
          source: TypistTech/dpl
          branch: add-wordpress-plugin-deployment
        slug: sunny
        username: tangrufus
        build_dir: build
        assets_dir: assets
        on:
          tags: true
    - <<: *deploy_default
      env: DEPLOY=GITHUB_NIGHTLY_BRANCH
      deploy:
        provider: build-branch
        edge:
          source: TypistTech/dpl
          branch: add-build-branch
        github_token: $GITHUB_ACCESS_TOKEN
        local_dir: build
        target_branch: nightly
        project_name: "Sunny"
        on:
          branch: master
  allow_failures:
    - env: WP_VERSION=nightly
  fast_finish: true
